import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LoaderWrapper from "../components/LoaderWrapper"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wiggly Woo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoaderWrapper>{children}</LoaderWrapper>
      </body>
    </html>
  );
}
